name: Send a Tweet
on: 
  workflow_dispatch:
  schedule:
  - cron: "36 13 * * *"
    
jobs:
  calculate:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date.outputs.date }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - id: date
      run: python3 .github/workflows/message.py
  tweet:
    runs-on: ubuntu-latest
    needs: calculate
    steps:
    - uses: ethomson/send-tweet-action@v1
      with:
        status: ${{ needs.calculate.outputs.date }}
        consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
        access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
